//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExtraerDatosExcel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Horarios
    {
        public bool habilitado { get; set; }
        public byte hora { get; set; }
        public byte minuto { get; set; }
        public string nombre { get; set; }
        public byte ID { get; set; }
    }
}
