//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExtraerDatosExcel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Llaves
    {
        public int ID { get; set; }
        public Nullable<int> Colaborador { get; set; }
        public Nullable<int> Faltas { get; set; }
        public Nullable<int> Limite_Faltas { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<System.DateTime> Fecha_Inicial { get; set; }
    
        public virtual Colaboradores Colaboradores { get; set; }
    }
}
