//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExtraerDatosExcel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Maquinas
    {
        public int ID { get; set; }
        public string Numero { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> Departamento { get; set; }
        public Nullable<int> Dias_Vencimiento { get; set; }
        public Nullable<int> Tiempo_Minimo_Trabajo { get; set; }
        public Nullable<int> Tiempo_Inactividad { get; set; }
        public Nullable<bool> Verificar_Maquina { get; set; }
        public Nullable<bool> Baja { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> mantenimientoHoras { get; set; }
        public Nullable<int> Dias_Vencimiento_Maquina { get; set; }
        public Nullable<bool> Verificar_fechaPermiso_Maquina { get; set; }
    }
}
