//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExtraerDatosExcel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CAEMPRUEBASEntities : DbContext
    {
        public CAEMPRUEBASEntities()
            : base("name=CAEMPRUEBASEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Colaboradores> Colaboradores { get; set; }
        public DbSet<Horarios> Horarios { get; set; }
        public DbSet<Llaves> Llaves { get; set; }
        public DbSet<Maquinas> Maquinas { get; set; }
        public DbSet<Proceso> Proceso { get; set; }
        public DbSet<Tipo_Movimiento> Tipo_Movimiento { get; set; }
        public DbSet<Tipo_proceso> Tipo_proceso { get; set; }
    }
}
